server:
  port: 8183

domain:
  payment:
    name: payment

mybatis:
  config-location: mybatis-config-h2.xml

spring:
  application:
    name: awesome-payment-service

  jpa:
    hibernate.ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb;MODE=MYSQL;
    username: sa
    password: null
    driver-class-name: org.h2.Driver
    initialization-mode: always
  h2:
    console:
      enabled: true
  # jpa:
  #   hibernate.ddl-auto: create
  #   show-sql: true
  #   database-platform: org.hibernate.dialect.MariaDB103Dialect
  # datasource:
  #   driver-class-name: org.mariadb.jdbc.Driver
  #   url: jdbc:mariadb://localhost:3300/payments?characterEncoding=UTF-8
  #   username: root
  #   password: skcc
  #   platform: mariadb
  #   initialization-mode: always
  #   continue-on-error: true

  cloud:
    stream:
      rabbit:
        bindings:
          orderCanceled:
            consumer:
              autoBindDlq: true
              bindingRoutingKey: order.OrderCanceled.#
          orderCreated:
            consumer:
              autoBindDlq: true
              bindingRoutingKey: order.OrderCreated.#
          paymentOutput:
            producer:
              routing-key-expression: headers['routeTo']
      binders:
        rabbitmq:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                #host: rabbitmq
                host: localhost
                port: 5672
                username: labs
                password: awesome-rabbitmq
      bindings:
        orderCanceled:
          destination: orderExchange
          group: payment.orderCanceled
          content-type: application/json
        orderCreated:
          destination: orderExchange
          group: payment.orderCreated
          content-type: application/json
        paymentOutput:
          destination: paymentExchange
          content-type: application/json
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
